=== KAWTARDAKHAM/XML/Data/tasks.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://ensias.ma/tasks"
           xmlns:tns="http://ensias.ma/tasks"
           elementFormDefault="qualified">


  <xs:element name="tasks">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="task" type="tns:TaskType"
                    minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="TaskType">
    <xs:sequence>
      <xs:element name="titre"       type="xs:string"/>
      <xs:element name="date_debut"  type="xs:date"/>
      <xs:element name="date_fin"    type="xs:date"/>
      <xs:element name="priorite"    type="tns:PrioriteType"/>
      <xs:element name="statut"      type="tns:StatutType"/>
      <xs:element name="sous_taches" type="tns:SousTachesType"
                  minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="id"   type="xs:ID"        use="required"/>
    <xs:attribute name="type" type="tns:TypeTache" use="required"/>
  </xs:complexType>


  <xs:complexType name="SousTachesType">
    <xs:sequence>
      <xs:element name="sous_tache" type="tns:SousTacheType"
                  minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="SousTacheType">
    <xs:sequence>
      <xs:element name="titre"  type="xs:string"/>
      <xs:element name="date_debut" type="xs:date"/>
      <xs:element name="date_fin"   type="xs:date"/>
      <xs:element name="statut" type="tns:StatutType"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
  </xs:complexType>

  <xs:simpleType name="TypeTache">
    <xs:restriction base="xs:string">
      <xs:enumeration value="simple"/>
      <xs:enumeration value="complexe"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="StatutType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="en cours"/>
      <xs:enumeration value="terminé"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="PrioriteType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="basse"/>
      <xs:enumeration value="moyenne"/>
      <xs:enumeration value="haute"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== KAWTARDAKHAM/XML/Data/task.xml
<?xml version="1.0" encoding="UTF-8"?>

<tasks xmlns="http://ensias.ma/tasks"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://ensias.ma/tasks ../Data/tasks.xsd">


  <task id="t1" type="simple">
    <titre>Terminer Etape 1 XML</titre>
    <date_debut>2026-06-02</date_debut>
    <date_fin>2026-06-03</date_fin>
    <priorite>haute</priorite>
    <statut>en cours</statut>
  </task>

   <task id="t2" type="simple">
    <titre>Rediger Rpport TP Python</titre>
    <date_debut>2026-06-03</date_debut>
    <date_fin>2026-06-04</date_fin>
    <priorite>basse</priorite>
    <statut>en cours</statut>
  </task>

  <task id="t3" type="complexe">
    <titre>Préparer le projet XML</titre>
    <date_debut>2026-06-01</date_debut>
    <date_fin>2026-06-07</date_fin>
    <priorite>haute</priorite>
    <statut>en cours</statut>
    <sous_taches>
      <sous_tache id="t31">
        <titre>Créer le fichier XSD</titre>
        <date_debut>2026-06-03</date_debut>
        <date_fin>2026-06-04</date_fin>
        <statut>terminé</statut>
      </sous_tache>
      <sous_tache id="t32">
        <titre>Écrire le fichier XML</titre>
        <date_debut>2026-06-04</date_debut>
        <date_fin>2026-06-05</date_fin>
        <statut>terminé</statut>
      </sous_tache>
      <sous_tache id="t33">
        <titre>Coder app.py</titre>
        <date_debut>2026-06-05</date_debut>
        <date_fin>2026-06-06</date_fin>
        <statut>en cours</statut>
      </sous_tache>
    </sous_taches>
  </task>

  <task id="t4" type="complexe">
    <titre>Préparer la soutenance</titre>
    <date_debut>2026-06-10</date_debut>
    <date_fin>2026-06-20</date_fin>
    <priorite>moyenne</priorite>
    <statut>en cours</statut>
    <sous_taches>
      <sous_tache id="t41">
        <titre>Préparer les slides</titre>
        <date_debut>2026-06-10</date_debut>
        <date_fin>2026-06-15</date_fin>
        <statut>en cours</statut>
      </sous_tache>
      <sous_tache id="t42">
        <titre>Rédiger le rapport</titre>
        <date_debut>2026-06-15</date_debut>
        <date_fin>2026-06-20</date_fin>
        <statut>en cours</statut>
      </sous_tache>
    </sous_taches>
  </task>


</tasks>
